name: arabic_font
description: Flutter package allows you to add arabic fonts in your flutter projects
version: 0.0.9
homepage: https://github.com/abom-me/arabic_font
issue_tracker: https://github.com/abom-me/arabic_font/issues
screenshots:
  - description: 'arabic font and Flutter logos.'
    path: screenshots/logo.png

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
        - asset: assets/fonts/Amiri/Amiri-BoldItalic.ttf
        - asset: assets/fonts/Amiri/Amiri-Italic.ttf
    - family: Aref_Ruqaa
      fonts:
        - asset: assets/fonts/Aref_Ruqaa/ArefRuqaa-Bold.ttf
        - asset: assets/fonts/Aref_Ruqaa/ArefRuqaa-Regular.ttf
    - family: Baloo_Bhaijaan
      fonts:
        - asset: assets/fonts/Baloo_Bhaijaan/BalooBhaijaan-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa/Changa-Bold.ttf
        - asset: assets/fonts/Changa/Changa-ExtraBold.ttf
        - asset: assets/fonts/Changa/Changa-ExtraLight.ttf
        - asset: assets/fonts/Changa/Changa-Light.ttf
        - asset: assets/fonts/Changa/Changa-Medium.ttf
        - asset: assets/fonts/Changa/Changa-Regular.ttf
        - asset: assets/fonts/Changa/Changa-SemiBold.ttf
    - family: El_Messiri
      fonts:
        - asset: assets/fonts/El_Messiri/ElMessiri-Bold.ttf
        - asset: assets/fonts/El_Messiri/ElMessiri-Medium.ttf
        - asset: assets/fonts/El_Messiri/ElMessiri-Regular.ttf
        - asset: assets/fonts/El_Messiri/ElMessiri-SemiBold.ttf
    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan/Harmattan-Regular.ttf
    - family: Jomhuria
      fonts:
        - asset: assets/fonts/Jomhuria/Jomhuria-Regular.ttf
    - family: Katibeh
      fonts:
        - asset: assets/fonts/Katibeh/Katibeh-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar/Lalezar-Regular.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef/LateefRegOT.ttf
    - family: Lemonada
      fonts:
        - asset: assets/fonts/Lemonada/Lemonada-Bold.ttf
        - asset: assets/fonts/Lemonada/Lemonada-Light.ttf
        - asset: assets/fonts/Lemonada/Lemonada-Regular.ttf
        - asset: assets/fonts/Lemonada/Lemonada-SemiBold.ttf
    - family: Mada
      fonts:
        - asset: assets/fonts/Mada/Mada-Black.ttf
        - asset: assets/fonts/Mada/Mada-Bold.ttf
        - asset: assets/fonts/Mada/Mada-ExtraLight.ttf
        - asset: assets/fonts/Mada/Mada-Light.ttf
        - asset: assets/fonts/Mada/Mada-Medium.ttf
        - asset: assets/fonts/Mada/Mada-Regular.ttf
        - asset: assets/fonts/Mada/Mada-SemiBold.ttf
    - family: Markazi_Text
      fonts:
        - asset: assets/fonts/Markazi_Text/MarkaziText-Regular.ttf
    - family: Mirza
      fonts:
        - asset: assets/fonts/Mirza/Mirza-Bold.ttf
        - asset: assets/fonts/Mirza/Mirza-Medium.ttf
        - asset: assets/fonts/Mirza/Mirza-Regular.ttf
        - asset: assets/fonts/Mirza/Mirza-SemiBold.ttf
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas/Rakkas-Regular.ttf
    - family: Reem_Kufi
      fonts:
        - asset: assets/fonts/Reem_Kufi/ReemKufi-Regular.ttf
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/Scheherazade/Scheherazade-Bold.ttf
        - asset: assets/fonts/Scheherazade/Scheherazade-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          
          
    - family: DINNextLTArabic
      fonts:
        - asset: assets/fonts/DinNextLTArabic/ArbFONTS-DINNextLTArabic-Black-3.ttf
        - asset: assets/fonts/DinNextLTArabic/ArbFONTS-DINNextLTArabic-Bold-2.ttf
        - asset: assets/fonts/DinNextLTArabic/ArbFONTS-DINNextLTArabic-Heavy-1.ttf
        - asset: assets/fonts/DinNextLTArabic/ArbFONTS-DINNEXTLTARABIC-LIGHT-1.ttf
        - asset: assets/fonts/DinNextLTArabic/ArbFONTS-DINNextLTArabic-Medium-2.ttf
        - asset: assets/fonts/DinNextLTArabic/ArbFONTS-DINNextLTArabic-Regular-2.ttf
          
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai/Dubai-Bold.ttf
        - asset: assets/fonts/Dubai/Dubai-Light.ttf
        - asset: assets/fonts/Dubai/Dubai-Medium.ttf
        - asset: assets/fonts/Dubai/Dubai-Regular.ttf
          
          
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/ibm/IBMPlexArabic-Text.ttf

    - family: Avenir Arabic
      fonts:
        - asset: assets/fonts/Avenir_Arabic/Avenir-Arabic-Medium.ttf
        - asset: assets/fonts/Avenir_Arabic/Avenir-Arabic-Book.ttf
        - asset: assets/fonts/Avenir_Arabic/Avenir-Arabic-Black.ttf
        - asset: assets/fonts/Avenir_Arabic/Avenir-Arabic-Heavy.ttf
        - asset: assets/fonts/Avenir_Arabic/Avenir-Arabic-Regular.ttf







